FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/package.json
RUN corepack enable && pnpm install --ignore-scripts
EXPOSE 3000
CMD ["pnpm", "dev:api"]
